# This file is for specifying options for this platform

set(ECHO_UI_FRAMEWORK "GX")
set(ECHO_AUDIO_SYSTEM "DSP")
set(BUILD_WITH_OPENGL OFF)
set(BUILD_TESTS OFF)
set(BUILD_TOOLS OFF)
set(BUILD_GRAPHICS_TESTS OFF)
set(BUILD_WITH_WEBSOCKETS OFF)
set(BUILD_WITH_SOCKETS ON)
set(BUILD_WITH_FREETYPE ON)
set(BUILD_WITH_SSL OFF)
set(BUILD_WITH_PROTOBUF_LITE ON)

set(CMAKE_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/${ECHO_TARGET_PLATFORM}-toolchain.cmake")
message("CMAKE_TOOLCHAIN_FILE " ${CMAKE_TOOLCHAIN_FILE})
set(CAPNP_EXECUTABLE "$ENV{ECHO_ENGINE_INSTALL_DIR}/linux/bin/capnp")
set(CAPNP_GENERATE_CPP "$ENV{ECHO_ENGINE_INSTALL_DIR}/linux/bin/capnp")
set(CAPNPC_CXX_EXECUTABLE "$ENV{ECHO_ENGINE_INSTALL_DIR}/linux/bin/capnpc-c++")
