LOCAL_PATH := $(call my-dir)

include $(ECHO_ENGINE_INSTALL_DIR)/env/Android-prebuild.config

#Include all libraries
include $(ECHO_ENGINE_INSTALL_DIR)/targets/Android/LibsAndroid.mk

include $(CLEAR_VARS)
LOCAL_MODULE := ECHO_ANDROID_TEMPLATE_APPLICATION_CLASS_NAME
LOCAL_SRC_FILES := ../../../dist/Android/libECHO_ANDROID_TEMPLATE_APPLICATION_LOWER_CLASS_NAME.a
include $(PREBUILT_STATIC_LIBRARY)

###########################
#Settings to build shared library

include $(CLEAR_VARS)

LOCAL_MODULE := ECHO_ANDROID_TEMPLATE_APPLICATION_CLASS_NAMEMain
LOCAL_C_INCLUDES := $(ECHO_VAR_ANDROID_MK_LOCAL_C_INCLUDES)
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_C_INCLUDES)

LOCAL_SRC_FILES := \
	$(ECHO_VAR_ANDROID_MK_LOCAL_SRC_FILES) \
	$(subst $(LOCAL_PATH)/,, \
	$(wildcard $(LOCAL_PATH)/../src/*.cpp))

LOCAL_CPP_FEATURES += $(ECHO_VAR_ANDROID_MK_LOCAL_CPP_FEATURES)
LOCAL_CFLAGS += $(ECHO_VAR_ANDROID_MK_LOCAL_CFLAGS)
LOCAL_LDLIBS := $(ECHO_VAR_ANDROID_MK_LOCAL_LDLIBS)
LOCAL_SHARED_LIBRARIES := 
LOCAL_STATIC_LIBRARIES := ECHO_ANDROID_TEMPLATE_APPLICATION_CLASS_NAME $(ECHO_VAR_ANDROID_MK_LOCAL_STATIC_LIBRARIES)

include $(BUILD_SHARED_LIBRARY)
