#! /bin/bash

echo "-====================================-"
echo "Echo automated dependency X clean script"
echo "-====================================-"

if [ "$1" = "?" ] ; then
	echo "$0 [library]"
	echo ""
	echo "If you specify a 'library' then only that library is removed."
	echo ""
	echo "-====================================-"
	exit 1;
fi

ONLY_LIB=$1

if [ "$ONLY_LIB" = "" ] ; then
	# Clean all
	echo "Removing X folder"
	rm -R "X"
	echo "Creating new X folder"
	mkdir "X"
else
	# Clean one
	echo "Removing X/$ONLY_LIB"
	rm -R "X/$ONLY_LIB"
	echo "Removing X/$ONLY_LIB.tar.gz"
	rm -R "X/$ONLY_LIB.tar.gz"
fi
echo "Done"
